dist: trusty
sudo: required

language: php

git:
  depth: 1

php:
  - 5.6
  - 7.1

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin
    - COMPOSER_MEMORY_LIMIT=2G

install:
  - composer self-update
  - composer install
  - phantomjs --webdriver=4444 > /dev/null &

before_script:
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path=`which true`" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - run drupal:site-install
  - drush --root=$PWD/build --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s

script:
  - composer grumphp
  - composer behat

notifications:
  email: false

before_deploy:
  - run release:create-archive
  - run changelog:generate --token=$CHANGELOG_GITHUB_TOKEN --tag=$TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: q7+KXdo1a/AQM4vFPePO/tp3KCKWBBkwWEkVtYTVX1WQ4AuY0HNgtxCl52KcdMQoR+9VNv9aTu76ryt/KXhARzOtpQ5dB3WXj9m04Jz4LPqXEJGtkC1pH0++6cv7x3GEu3K3VqV6RTZ1XR55hY3bIGlXa2ZUEX3VKRclmBtvCiECA74rAeLD85JWWvkQeUrSUnrcNSlOoUR4UVplltZrvGzTnA00+Ys/BtLHZS/eIIM3VlMUaLXtzxtZSsr5eK8vyvzd6iTj2EA4JBdmyiMjmk1sn3UswbVUWC4GR14k6n6mI3z+8rxwPjOBokGnK0DCTZ+9vGZqUIvSqwURlVE3+TK30553eymt6lGL4AQj/0OCofE0ldevxC4hI4b8n6w63sZN7/1UslOYnzLb39aBvSgYl75po63lm/WF2WD6xbveBklmLbH4FCZRWPu/6EU7HfradCqJKJo2cfStVyxhNxG6CxO+ep4//zHe2eXYdl//z1Rw7yQgClPnS1ptVjJYkJwPipw1QI4IDtcuO1hUs7TFdbFn4Bl24bKsE3S6nV+zev+Ge14vqhvDnA4V6eqx1a0ORhZz3IqIANJt1wyhdZRB4BsYrKMdPjVUzxftGuv8xTJJ6JGDJ9B10wGmDyAipiSr+TY964cADYXrG68Rt63SMHirjl7dViPfUe4WlAw=
  file_glob: true
  file:
   - ec_europa-*.tar.gz
   - CHANGELOG.md
  skip_cleanup: true
  on:
    repo: ec-europa/ec_europa
    tags: true
